#!/usr/bin/env bash
#redirescts NGINX
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' | sudo tee /var/www/html/index.html
sed -i '/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo service nginx start
