#!/usr/bin/env bash
#redirescts NGINX
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' | sudo tee /var/www/html/index.html
sed -i " ^/redirect_me" /etc/nginx/sites-available/default 
sudo service nginx start
