#!/usr/bin/env bash
# 404 redirescts NGINX
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' | sudo tee /var/www/html/index.html
sed -i "^/redirect_me" /etc/nginx/sites-available/default 
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i "error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx start
