#!/usr/bin/env bash
#Nginx likes port 80
# rm /etc/nginx/sites-enabled/mysite.com
# ln -s /etc/nginx/sites-available/mysite.com /etc/nginx/sites-enabled/mysite.com
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
