#!/usr/bin/env bash
#Bash script that:

#+Creates the file /var/run/myscript.pid containing its PID
#+Displays To infinity and beyond indefinitely
#+Displays I hate the kill command when receiving a SIGTERM signal
#+Displays Y U no love me?! when receiving a SIGINT signal
#+Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > myscript.pid
mv myscript.pid /var/run/

trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid ; pkill -9 -f '100-process_and_pid_file'" SIGTERM
trap "rm /var/run/myscript.pid ; pkill -9 -f '100-process_and_pid_file'" SIGQUIT

while true
do
echo "To infinity and beyond"
done
