#!/usr/bin/env bash
#displays BASH pid
# shellcheck disable=SC2009
# shellcheck disable=SC2034  # Unused variables left for readability
file="top"
while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12
do
if [[ "$f12" == *"bash"* ]];then
printf"%s %s\n" "$f2""$f12"
fi
done<<<"$file"

