#!/usr/bin/env bash
#Bash script that displays:
#+To infinity and beyond indefinitely
#+With a sleep 2 in between each iteration
#+I am invincible!!! when receiving a SIGTERM signal
handle_sigter(){
	echo "I am invincible!!!"
}
#trapping the SIGTERM and redirecting it to handle_sigterm function
trap handle_sigterm SIGTERM

while true
do
echo "To infinity and beyond"
sleep 2
done
