#!/usr/bin/env bash
#loops 10 times and displays custom message at interval 4 and 8
i=1
while [ $i -le 10 ]
do
if [ $i == 4 ];then
echo "bad luck"
elif [ $i == 8 ];then
echo "good luck"
else
echo "Best School"
fi
((i += 1))
done
