#!/usr/bin/env bash
#Gives information about school file
#if [ $# -eq 0 ];then 
file="school"
if [ ! -e $file ];then 
echo "school file does not exist"
else
echo "school file exists"
if [ ! -s $file ];then 
echo "school file is empty"
fi
if [ -s $file ];then 
echo "school file is not empty"
fi
if [ -f $file ];then 
echo "school is a regular file"
fi
fi
