#!/usr/bin/env bash
#makes nginx default user of nginx conf files
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx restart
